### ISSUE TITLE
Presence device android 4.42

### ISSUE THREAD

**Issue by p4co86** [dgmltn/android-pimatic-app#16]
On android 4.4.2 all presence devices showpresence, but there are not all presence. It doesent matter if device is on or off it allways shows the full dot

**Comment by dgmltn** [comment]
Does it not fade to gray if absent, and orange if present on your device?

**Comment by p4co86** [comment]
Exactlly, it is allways orange.

**Comment by dgmltn** [comment]
Fixed here: 9551233
