### ISSUE TITLE
Sometimes no connection

### ISSUE THREAD

**Issue by p4co86** [dgmltn/android-pimatic-app#18]
After a few connections to the server it seems that thr config not load. When i then add the demo server it works allways, doesent matter how often i connect to the demo server. Mine works just two times, sometimes more.

**Comment by p4co86** [comment]
Delete the account and readd it, doesent change the problem

**Comment by p4co86** [comment]
seems that the config needs very long to load. now i have no succes to connect to my pimatic server.

**Comment by dgmltn** [comment]
Do you have a large config file? See if 5d16bc9 improves your connection.

**Comment by p4co86** [comment]
i test it later, yes  i think i have a large config file. 
could you publish it on googleplay, so it is easyier and faster to test it, then i could test it now.
